database:
  host: 127.0.0.1
  port: 3306
  schema: upay_core
  serviceId: 100
  username: root
  password: root
  tables:
    - name: merchant
      columns:
        - id
        - name
      primaryKey: id
      esIndex: upay_core_test
      esType: merchant
elasticSearch:
  url: http://127.0.0.1:9200
  username: wkx
  password: 123
